have config file in data to retain it on updates
git-svn-id: svn://10.222.10.12/src1/avnav@444 981887c0-d8ae-4743-aaa6-7abdade54d40

diff --git a/avnav_raspberry/avnav b/avnav_raspberry/avnav
--- a/avnav_raspberry/avnav
+++ b/avnav_raspberry/avnav
@@ -23,7 +23,8 @@ DESC="AV nav server"
 NAME=avnav
 BASEDIR=/home/pi/avnav
 DAEMON=$BASEDIR/program/server/avnav_server.py
-CONFIG=$BASEDIR/program/raspberry/avnav_server.xml
+CONFIG=$BASEDIR/data/avnav_server.xml
+BASECONFIG=$BASEDIR/program/raspberry/avnav_server.xml
 
 #set -x
 
@@ -71,6 +72,15 @@ do_start()
 	  do
 	  	iptables -A PREROUTING -t nat -p tcp -d $addr --dport 80 -j REDIRECT --to-ports $FORWARD
 	  done
+	fi
+	if [ ! -f $CONFIG ] ; then
+		log "trying to intialize $CONFIG"
+		cp $BASECONFIG $CONFIG 
+		if [ $? != 0 ] ; then
+			log_daemon_msg "unable to create $CONFIG"
+			return 1
+		fi
+		chown pi $CONFIG
 	fi
 	su -c "$DAEMON $CONFIG" pi >/dev/null 2>&1 &
 }
