correctly create basedir

diff --git a/linux/avnav b/linux/avnav
--- a/linux/avnav
+++ b/linux/avnav
@@ -75,12 +75,11 @@ if [ "$basedir" = "" ] ; then
   if [ -d $basedir/data ] ; then
     basedir=$basedir/data
     echo "using old style basedir $basedir"
-  else
-    if [ ! -d $basedir ] ; then
-        echo "creating $basedir"
-        mkdir -p $basedir || err "unable to create $basedir"
-    fi
   fi
+fi
+if [ ! -d $basedir ] ; then
+    echo "creating $basedir"
+    mkdir -p $basedir || err "unable to create $basedir"
 fi
 basedir=`readlink -f $basedir`
 for d in log charts routes tracks ; do
