correctly use python3 for check in gui mode

diff --git a/linux/avnav b/linux/avnav
--- a/linux/avnav
+++ b/linux/avnav
@@ -135,8 +135,8 @@ if [ "$xmlfile" = "" ] ; then
   fi
 fi
 if [ "$gui" != 0 ] ; then
-  python -c 'import wx' > /dev/null 2>&1
-  [ $? != 0 ] && err "missing package python-wxgtkn.n, please install a valid version of this package (e.g. python-wxgtk3.0)"
+  python3 -c 'import wx' > /dev/null 2>&1
+  [ $? != 0 ] && err "missing package python3-wxgtkn.n, please install a valid version of this package (e.g. python3-wxgtk3.0)"
   exec $guiprog -b "$basedir" -u "viewer=$viewer,libraries=$avnavdir/viewer/libraries,sounds=$avnavdir/sounds"
 else
   echo "chartdir=$chartdir, basedir=$basedir, config=$xmlfile, starting server..."
