1st successful installation on trixie image

diff --git a/raspberry/postinstall b/raspberry/postinstall
--- a/raspberry/postinstall
+++ b/raspberry/postinstall
@@ -1,20 +1,24 @@
 #! /bin/sh
 BASE=/usr/lib/avnav/raspberry
-startAvNav=1
-systemctl -q status avnav > /dev/null || startAvNav=0 
-systemctl stop avnav || echo "avnav not running"
-systemctl stop check_parts || echo "check_parts not running"
-systemctl stop check_wlan || echo "check_wlan not running"
-rm -f /etc/init.d/avnav
-rm -f /etc/init.d/check_wlan
-rm -f /etc/init.d/check_parts
+startAvNav=0
+if systemctl -q is-active avnav ; then
+  startAvNav=1
+else
+  echo "avnav not running"
+fi
+if [ "$startAvNav" = 1 ] ; then
+    systemctl stop avnav || echo "avnav not running"
+else
+    echo
+fi
+
 VERSIONFILE=$BASE/raspi.version
 if [ -f $VERSIONFILE ] ; then
     . $VERSIONFILE
 fi
 PATCHCMD=$BASE/patchServerConfig.py
 systemctl daemon-reload
-systemctl enable avnav
+systemctl enable avnav || echo "cannot enable avnav service"
 echo stopping and disabling gpsd
 systemctl disable gpsd || echo ' ' > /dev/null
 systemctl stop gpsd || echo '' > /dev/null
@@ -42,23 +46,6 @@ if [ -f $CONFIG ] ; then
 else
     echo "no old config $CONFIG found to migrate"
 fi
-grep "^ *FSCKFIX *= *yes" /etc/default/rcS > /dev/null || ( echo "configure FSCKFIX=yes"; echo 'FSCKFIX=yes' >> /etc/default/rcS)
-
-#remove dhcp server ntp conf
-DHCONF=/var/lib/ntp/ntp.conf.dhcp
-if [ -f $DHCONF ] ; then
-    echo "removing $DHCONF"
-    rm -f $DHCONF
-fi
-[ ! -d var/lib/ntp/ ] && mkdir -p var/lib/ntp/
-#a bit dirty trick to force ntpd to use our config file
-cp $BASE/ntp.conf $DHCONF
-HOOK=/etc/dhcp/dhclient-exit-hooks.d/ntp
-if [ -f $HOOK ] ; then
-    echo "moving $HOOK into /etc/dhcp/save"
-    [ ! -d /etc/dhcp/save ] && mkdir /etc/dhcp/save
-    mv $HOOK /etc/dhcp/save
-fi
 
 BOOTCFG=/boot/avnav.conf
 if [ -d /boot/firmware ]
@@ -71,15 +58,13 @@ if [ ! -e "$BOOTCFG" ] ; then
     cp $BASE/avnav.conf $BOOTCFG
 fi    
 
-systemctl disable dhcpd || echo "dhcpd not running, dont need to disable"
-systemctl stop dhcpd || echo "dhcpd not running, dont need to disable"
-systemctl disable dhcpcd || echo "dhcpcd not running, dont need to disable"
-systemctl stop dhcpcd || echo "dhcpcd not running, dont need to disable"
-systemctl disable --now ntp || echo "ntp not running, dont need to disable"
-systemctl mask ntp || echo "ntp not running, dont need to mask"
-systemctl disable --now ntpsec || echo "ntpsec not running, dont need to disable"
-systemctl mask ntpsec || echo "ntpsec not running, dont need to mask"
-
+TO_DISABLE="systemd-timesyncd"
+for service in $TO_DISABLE
+do
+    if systemctl --quiet is-enabled $service ; then
+        systemctl disable --now $service || echo "unable to disable $service"
+    fi
+done
 
 systemctl daemon-reload
 if [ "$startAvNav" = "1" ] ; then
